### ISSUE TITLE
OBO Importer handle updates

### ISSUE THREAD

**Issue by Mimickal** [tair/toastdos-back#12]
We already have the initial import stuff done, but we also need to be able to update existing terms.
Note that users can only add new keywords. They cannot add new keyword types or synonyms.

 - Don't delete user-added terms (terms without external IDs)
 - Update names for existing terms
 - ~~Terms from a previous OBO file (terms with external IDs) NOT present in the new OBO file~~ handled in tair/toastdos-back#128 
 - User added term in DB without ID might show up in new OBO
  - Would show up as existing name without an ID
  - Match new information from obo into existing term
  - Should be treated as OBO terms from that point on
 - Synonyms not present in obo file should be removed

Acceptance Criteria:
 - Stale synonyms are deleted
 - User added terms are never deleted
 - ~~Initially user added OBO terms are updated when they show up in OBO~~

**Comment by JDonut** [comment]
Deprecated keyword referenced by annotation should alert curators about that annotation
