### ISSUE TITLE
OBO diff with context

### ISSUE THREAD

**Issue by JDonut** [tair/toastdos-back#16]
We need to compare two Gene Ontology obo files and see what changed between the two. This will help us with updating our database of keywords.

The "diff" portion:
Can probably be completed with the UNIX diff utility.
Might be worthwhile to look into other diff utilities.

The "with context" portion:
We also want to see which obo term that line belongs to.

For example, if a line "synonym: abc" changed to "synonym: abcdefg", I want the diff output to be
```
[Term]
id: GO:0000001
name: thingy with a name
namespace: whatever
synonym: abcdefg
is_a: GO:000001234
```

Acceptance Criteria:
 - Successfully finds updated lines between two obo files
 - Output includes the entire term the change belongs to
 - Only looks at "Term" terms. Ignore things like "TypeDef"
 - There is no extraneous stuff above / below the term output
 - A demo showing it off

**Comment by JDonut** [comment]
Entire terms can be removed between obo updates. The diff tool should take note of entire terms being removed, and cache their IDs. When finished with the diff generation, also output that list of IDs to another file.

**Comment by bob-muller** [comment]
Note that you need to take care of term uses in annotations too, when a term is removed.

**Comment by JDonut** [comment]
Referential integrity will be maintained by setting a "deleted" flag to true, rather than actually removing the data from the database. 

We can figure out what to do with annotations with deleted keywords once we start talking about the curation side of things.
