### ISSUE TITLE
Submitter notification

### ISSUE THREAD

**Issue by TechnicalFox** [tair/toastdos-back#180]
Two parts
1. Notification upon submission (your annotations have been submitted and will be reviewed) and 

2. Submitter is notified via email when a submission they created is completely reviewed by a curator.

Acceptance Criteria:
  - Submitter receives email when submission they created is submitted
-Submitter receives email when submission is fully reviewed
Story Points: 5

**Comment by lreiser** [comment]
Need to think about how we ensure that we have gathered users email address for notification.
1. They may have entered in email when first logging in via ORCiD
2. Or we ask them before completing submission to give email address for notifications.
