### ISSUE TITLE
User data export

### ISSUE THREAD

**Issue by TechnicalFox** [tair/toastdos-back#182]
Authenticated user can export data from the database and download it.

Acceptance Criteria:
  - User can download a file in multiple formats containing the data in the database.
    - Gene Ontology GPAD Format
    - Plant Ontology GAF Format

Story Points: 2

**Comment by lreiser** [comment]
MVP1 is dump all approved annotations
MVP2 is to be able to filter the exported annotations.

**Comment by bgrawi** [comment]
This is being closed as now users can view and download exports from the site, and the daemon is working correctly. 
See: #265 #266
