### ISSUE TITLE
Add evidence field to annotation 

### ISSUE THREAD

**Issue by bgrawi** [tair/toastdos-back#185]
A submitter should be able to add supporting evidence to an annotation for certain annotation types (TBD).

This field will be shown next to the other annotation fields and will validate against other locus types.

Acceptance Criteria:

- Given a certain annotation type, a submitter can type in related evidence in the form of another locus id
Story Point: 3

**Comment by tberardini** [comment]
After discussion with @lreiser, we need to modify the schema to allow for more than one locus identifiers to be used as supporting evidence.  Currently, the GeneTermAnnotation table models only ONE evidence_id (this is the key for supporting evidence, refers to Locus table). However, sometimes, more than one evidence_id needs to be added. 

Suggested solution:

Update schema to add a linking table between GeneTermAnnotation (GTA) and Locus. Remove evidence_id from GTA table.

**Comment by tberardini** [comment]
Also, enable usage of CheBI id/s for chemicals in the evidence_with.  This is as an alternative to being able to use locus id/s.

http://purl.obolibrary.org/obo/chebi.obo

**Comment by lreiser** [comment]
Evidence with needs to allow for AND/OR relationship. So when a user is prompted to add evidence with for an IGI or ProteinProtein (IPI )annotation AND there is more than one evidence with they are also able to choose (via drop down selector) if it is AND or OR. 

This also affects the export of Evidence With (which still needs to be done) in the data export.
The AND relation is indicated with a comma (eg. AGI_LocusCode:AT1G02300, AGI_LocusCode:At5G01010)
The OR relation is indicated with a pipe (e.g. UniProtKB:Q34T68|UniProtKB:J45H89)

**Comment by tberardini** [comment]
After checking - it is better to NOT allow mixing and matching of AND and OR relations.

**Comment by lreiser** [comment]
@tberardini  thanks for checking.. I 'd never seen one in combination so that makes sense.
