### ISSUE TITLE
Saving in-progress submissions

### ISSUE THREAD

**Issue by bgrawi** [tair/toastdos-back#186]
In the submission process, changes are automatically saved so if the user leaves the page or closes their browser, the information will be repopulated the next time they visit the page.

There appears to be draft functionality in the backed to support this already, but will require some more research.

Acceptance Criteria:
-  A submitter types information, closes their browser, reopens the submission page and their information is kept.
- Once the submission is submitted, the saved information is cleared.

Story Points: 3

**Comment by lreiser** [comment]
Question, how does a user see this when the log in again?
