### ISSUE TITLE
Get submission endpoint

### ISSUE THREAD

**Issue by Mimickal** [tair/toastdos-back#21]
Gets all of the needed records for a single submission. A submission is defined by all of the annotations that share a publication_id, submitter_id, and submission_date. See tair/toastdos-back#76 for details on submissions.

```
GET /api/submission?submitter_id=<sid>&publication_id=<pubid>&submission_date=<sdate>
```
Note that publication_id is our internal ID, not the pubmed ID or DOI

**Comment by JDonut** [comment]
Our existing schema has no way to figure out which submission was responsible for creating a GeneSymbol symbol / fullname pair. Completing this story will also require us to modify annotations to keep a reference to their added GeneSymbol rows. This will also affect the submission creation endpoint.
