### ISSUE TITLE
Ensure that GOAT is using the most recent ECO-GO mapping file for manual assertion evidence codes

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#220]
I noticed that some of the IGI evidence codes are not being displayed as options from GOAT. They seem to be the new evidence codes that Tanya requested to be added back in September 2017 that were included in the updated mapping file that was released on Oct 6, 2017.
I thought we had imported that data but perhaps it never got loaded?

As a reminder the file is located here...
http://purl.obolibrary.org/obo/eco/gaf-eco-mapping-derived.txt

**Comment by bgrawi** [comment]
Do you have an example code that was added?

**Comment by lreiser** [comment]
OK I uploaded a spreadsheet into the Google drive that has all of the  ECO methods that are currently mapped to GO evidence codes. Among those evidence codes the ones we use for manual literature curation are IDA, IPI, IGI, IMP and IEP. There are 237 of those 
We can further restrict the display of methods for the Protein Protein interactions to ONLY those that correspond to the IPI evidence code.

here is the spreadsheet.
https://drive.google.com/drive/u/0/folders/0BySFIS8pY8oqY0VsRk5WY2U3T1E
