### ISSUE TITLE
Create an improved homepage

### ISSUE THREAD

**Issue by GavinNishizawa** [tair/toastdos-back#235]
potentially based on user role

**Comment by lreiser** [comment]
Some features that we might want to consider being able to include to add interesting content to a home page 
1. Roll of recently curated papers, genes or submitters
2. Brief explanatory video or 'slideshow' that summarizes what the tool does (Phoenix to provide)

**Comment by bgrawi** [comment]
I think we are waiting for @lreiser to get a sketch or something back before working on this?
