### ISSUE TITLE
Add Evidence With to Data Export files

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#241]
Current implementation of the GAF data export does not include evidence with (column 8). Needs to include evidence with and allow for mutiples

1. Format
for AGI Locus ID format is AGI_LocusIdentifier:ID
for UniProt protein ID is  UniProtKB:ID
for RNACentral ID is RNACentral:ID

2. Format to specify And/Or
The AND relation is indicated with a comma (eg. AGI_LocusCode:AT1G02300, AGI_LocusCode:At5G01010)
The OR relation is indicated with a pipe (e.g. UniProtKB:Q34T68|UniProtKB:J45H89)

**Comment by GavinNishizawa** [comment]
Front end portion includes creating the UI to set the AND or OR relationship
