### ISSUE TITLE
Term autocomplete sorting

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#245]
When searching for terms in autocomplete the exact match should appear on the top

e.g. protein binding 

Also is there a cut off to the number of terms being suggested?

**Comment by GavinNishizawa** [comment]
Currently I think the number of terms coming back is limited to 20 ([ref](https://github.com/tair/toastdos-back/blob/66881512e9f23910beba75fad139f19c2f066020/app/controllers/keyword.js#L10)). Also, the results are currently not ordered in any useful way. 
NOTE: Improving the keyword search is related to #133.

**Comment by tberardini** [comment]
Seth Carbon <sjcarbon@lbl.gov>
Can talk to him about how Amigo filters search results.
amigo.geneontology.org
