### ISSUE TITLE
Update any tools accessing UniProt WebServices to use https instead of http

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#261]
Per this notification from UniProt
this changeover will happen in June so we should make any changes to ensure that all of our tools (e.g. Uniprot id checks) are working as expected.
http://www.uniprot.org/help/https_change

**Comment by GavinNishizawa** [comment]
It appears we are using the https link here:
https://github.com/tair/toastdos-back/blob/3e8a82715d180b65cc24d66acde57e745c9a5fda/app/lib/uniprot_api.js#L7
