### ISSUE TITLE
Reorder Exports to have most recent files at the top

### ISSUE THREAD

**Issue by tberardini** [tair/toastdos-back#274]
http://toastdos.phoenixbioinformatics.org/exports

Maybe even bin the files into months or some other solution to prevent the list from getting unmanageable.

**Comment by lreiser** [comment]
Actually is there a need for different 'versions' at all?
 I thought the file was going to be updated nightly and be cumuluative- so increasing in size each time.  So can't we just have the same file (name) be exported and replace the old w the new. 
Is there a use case for versioning? 
Will the annotations change once they are approved? Right now I can't think of a reason not to just overwrite.

**Comment by tberardini** [comment]
The dates of the annotations are in the file itself so that takes care of wanting to know when the annotations were made.  Are there drawbacks on the tech end for making a cumulative file as Leonore suggests?
