### ISSUE TITLE
Search annotations from a submitter

### ISSUE THREAD

**Issue by JKingSE** [tair/toastdos-back#306]
Points: 3
User Story:
As a user, I would like to be able to see all annotations from a submitter

**Comment by tberardini** [comment]
Works by name but not ORCID

nicholas works
0000-0003-0073-0858 does not work

**Comment by tberardini** [comment]
Searching with John gives weird results
![image](https://user-images.githubusercontent.com/4998871/53674525-74b4eb80-3c43-11e9-93ba-9c79e965b728.png)
