### ISSUE TITLE
conditional display of 'Evidence with' not working

### ISSUE THREAD

**Issue by tberardini** [tair/toastdos-back#312]
To reproduce: 
http://52.14.163.196:4200, login and go to submission

1. PMID  = 27095837
2. Locus = AT5G37820
3. Add a Biological process annotation for 'pollen germination'
4. Select an evidence, 'double mutant phenotype evidence used in manual assertion'.
5. No evidence with field shown.  

![image](https://user-images.githubusercontent.com/4998871/50366179-0f4ecb00-052d-11e9-9b0c-a0412f848684.png)

Compare with executing the same steps on toastdos.phoenixbioinformatics.org

![image](https://user-images.githubusercontent.com/4998871/50366164-0231dc00-052d-11e9-9df9-b90979cf5e83.png)

**Comment by tberardini** [comment]
related #185

**Comment by JKingSE** [comment]
The items we tested that we knew would need evidence now have it shown.  However, as seen in the meeting, there was at least one class of items that needed evidence that didn't have it.  That item was the item that started with "Double mutant".  We will look into that one, but need this reviewed for any other possible missing areas.

**Comment by lreiser** [comment]
Per this discussion. Any selected method that maps to the code IGI or IPI should trigger the 'evidence with box'.
mapping of ECO terms to GO evidence codes (e.g. IDA, IGI) here:
http://purl.obolibrary.org/obo/eco/gaf-eco-mapping-derived.txt

Also the default 'relationship' type should be AND. The first addition would always be AND. OR would be used only when including more than one gene in Evidence with.
I noticed the default display was OR. Should be like this.

![evidencewith](https://user-images.githubusercontent.com/14040923/52738248-16b9b000-2f83-11e9-9654-dd03d6098c78.png)

**Comment by lreiser** [comment]
Here is the set of restrictions to display.
This requires using the mapping file for ECO:GO (mapping ECO terms to the corresponding 3 letter evidence code which is in previously specified mapping file)

For each annotation (other than comment) the following restrictions apply 
**Annotation Type: Evidence Type(s)**
Protein Interaction: IPI
Molecular Function: IDA, IPI, IGI,IMP, EXP
Cellular Component: IDA, IEP, EXP
Biological Process:IDA, IMP, IGI, IPI, IEP, EXP
Structure/Growth Development (expression annotations): IEP, IDA, EXP

**Comment by lreiser** [comment]
FWIW when testing other scenarios I used an IGI evidence method (suppressor/enhancer interaction phenotypic evidence used in manual assertion) and was properly and appropriately presented with the 'Evidence with' but using a different  method (double mutant phenotypic evidence used in manual assertion) did not trigger the event. So it is inconsistent.

**Comment by JKingSE** [comment]
Using the reproduction steps above, this now appears.  I'm not sure of exactly what other ways to get evidence with to appear, so this would need to be further tested by the sponsors.

**Comment by JKingSE** [comment]
'phage display evidence used in manual assertion' shows up one time
'double mutant phenotype evidence used in manual assertion' shows up three times with the same code, but different synonyms
All other IGI codes are showing the evidence with section except for 'double mutant phenotype evidence used in manual assertion'.  
The ecomap file does not include 'double mutant phenotype evidence used in manual assertion'.
Evidence with shows up for eco codes matched to go codes.

**Comment by tberardini** [comment]
Opened ticket in ECO tracker:
https://github.com/evidenceontology/evidenceontology/issues/216

**Comment by lreiser** [comment]
Confirmed that double mutant evidence code now works to trigger the evidence with field.
![screenshot_1656](https://user-images.githubusercontent.com/14040923/55853274-2a157180-5b15-11e9-9889-a47ef52e30e5.png)
