### ISSUE TITLE
Protein Interaction annotation not working

### ISSUE THREAD

**Issue by tberardini** [tair/toastdos-back#313]
To reproduce:
http://52.14.163.196:4200, login and go to submission

1. PMID = 27095837
2. Add Locus 1 = AT5G37820
3. Add Locus 2 = AT5G37810
4. Add a Protein interaction annotation.  Select AT5G37820 and AT5G37810 as the two genes.
5. No methods available to select from, [object Object] is shown.

![image](https://user-images.githubusercontent.com/4998871/50366423-63a67a80-052e-11e9-98d3-eaa644bcfddd.png)

Compare with executing the same steps on toastdos.phoenixbioinformatics.org

![image](https://user-images.githubusercontent.com/4998871/50366345-f1359a80-052d-11e9-9ec2-d34f527d07c9.png)

**Comment by tberardini** [comment]
Cannot test fully.  Running into another bug (to be documented) related to submission. However, it looks like the right methods are showing up now.

**Comment by lreiser** [comment]
I see a very long list of methods displaying- more than what I think is covered by the IPI to ECO mapping.
![interactionevidence](https://user-images.githubusercontent.com/14040923/52678408-6a29f080-2ee6-11e9-85b0-e0547a4aaaa4.png)

**Comment by tberardini** [comment]
@qwertyflagstop What is the restriction (if any) on which ECO entries are displayed for this particular option (Protein Interaction annotation type)?

**Comment by tberardini** [comment]
Copied the relevant part from #312 

> Here is the set of restrictions on the evidence to display for Protein Interaction type annotations.
> This requires using the mapping file for ECO:GO (mapping ECO terms to the corresponding 3 letter evidence code which is in previously specified mapping file)
> 
> For each annotation (other than comment) the following restrictions apply
> _**Annotation Type: Evidence Type(s)**_
> **Protein Interaction: IPI**

**Comment by lreiser** [comment]
I think that this is now  SORT of working  in the sense that one can enter multiple loci and choose from drop down for protein interactions AND select an IPI method BUT there is a fundamental problem as soon as you try to review the annotation.
It is as if when there is more than one locus being annotated the data is not carried over to the submission screen.

**Comment by lreiser** [comment]
This does not appear to be fixed. 
Input looks fine but cannot submit

![screenshot_1614](https://user-images.githubusercontent.com/14040923/53776989-c14f2f80-3eac-11e9-9b0b-5584c5d43af6.png)

**Comment by lreiser** [comment]
Still seeing the same issue once I move to the review submission screen.
"Invalid annotation (no locus name)
FWIW I am testing in Firefox incognito mode.

![screenshot_1624](https://user-images.githubusercontent.com/14040923/53847253-c5d71f00-3f64-11e9-92b0-98d8df21d873.png)

**Comment by lreiser** [comment]
are we sure the fix was pushed to staging server?

**Comment by JKingSE** [comment]
There is a different issue happening with this issue now.  The first gene appears to auto populate with the first annotation, but the information isn't actually sent over when the annotation is submitted. For the information to be sent over, the user still has to click on the dropdown and select the first annotation in the Gene 1 box. Then it will work which might be why Nick saw it working.
1. PMID = 27095837
2. Add Locus 1 = AT5G37820
3. Add Locus 2 = AT5G37810
4. Add a Protein interaction annotation. 
5. For Gene 1, select AT5G37810 and then switch it back to AT5G37820.
6. For Gene 2, select AT5G37820.
7. Clicking submit should now work
It appears that the information only fills into the form when the option is changed and not in auto-population.

**Comment by JKingSE** [comment]
The fix for this bug is closer but not quite there.  A different issue occuring
Information entered:
PMID = 27095837
Add Gene 1 = AT5G37810
Add Gene 2 = AT5G37820
Add a Protein interaction annotation.
Gene 1 in annotation is auto-populated to AT5G37810
Manually set Gene 2 in annotations to AT5G37820
Add a method to the annotation
Click Review Submission

![Issue313](https://user-images.githubusercontent.com/17603890/55420440-0ebecb00-5545-11e9-9ee9-c8cf0989a46a.png)

**Comment by lreiser** [comment]
This is fixed. I am able to choose genes from the selector for a protein protein interaction and those selections are accurately represented in the review screen. 
![screenshot_1660](https://user-images.githubusercontent.com/14040923/55853943-01db4200-5b18-11e9-9709-4e1ab5a37a0b.png)
