### ISSUE TITLE
Initial load of submission form has data entered in Locus field

### ISSUE THREAD

**Issue by tberardini** [tair/toastdos-back#315]
To reproduce:
http://52.14.163.196:4200, login and go to submission
1. Enter PMID = 27095837
2. Without entering any data into 'Locus 1', click on 'Add Another Gene'
3. Compare the entries in Locus 1 and Locus 2.  Locus 1 is pre-populated with data, Locus 2 has 'suggested' data in greyed out font.
4. Locus 1 should also have 'suggested' data in greyed out font instead of the pre-populated data.
(5. Can you fix the typos of the missing '.' after g in e.g. in all cases?)

![image](https://user-images.githubusercontent.com/4998871/50366920-740c2480-0531-11e9-98ef-4fd90154d1f8.png)

**Comment by lreiser** [comment]
@tberardini  this seems to be resolved. The gene field is no longer populated with the sample data. If you agree, we can close.

**Comment by tberardini** [comment]
agreed.
