### ISSUE TITLE
Minor: typos in dropdown menu of annotation choices

### ISSUE THREAD

**Issue by tberardini** [tair/toastdos-back#316]
Please update 'Anotomical' to 'Anatomical' and 'SubCellular Location (Go...' to 'Subcellular Location (GO...' in all places.

![image](https://user-images.githubusercontent.com/4998871/50367047-2f34bd80-0532-11e9-8f9c-a203d799b85c.png)

**Comment by tberardini** [comment]
Bug looks fixed to me

**Comment by lreiser** [comment]
close?
