### ISSUE TITLE
Entering DOI does not properly validate article

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#317]
When entering a digital object identifier (DOI) the input form returns 'undefined' values for the title and author field. Entering a DOI is different than entering a PMID where the validation returns author and title.
The expected behavior when submitting a DOI is to return the URL. This allows a submitter to check that the DOI is associated to the correct article.

Attached are screenshots showing the current validation and what was previously implemented.
![screenshot_1493](https://user-images.githubusercontent.com/14040923/50455588-e307c580-0903-11e9-9e43-651cf7b769cb.png)
![screenshot_1494](https://user-images.githubusercontent.com/14040923/50455591-e602b600-0903-11e9-810f-7a11d1107031.png)

You can replicate the issue using this or any valid DOI
10.3389/fpls.2018.01721

**Comment by tberardini** [comment]
Bug looks fixed to me

**Comment by lreiser** [comment]
fixed
