### ISSUE TITLE
Minor: a few other typos in dropdown menu of annotation choices (GO vs Go, Subcellular vs SubCellular)

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#318]
Please update the dropdown for the localization to 
Subcellular location (GO Component)
from 
SubCellular location (Go Component)

![screenshot_1495](https://user-images.githubusercontent.com/14040923/50455857-902f0d80-0905-11e9-8fb0-d45d29649424.png)
![screenshot_1496](https://user-images.githubusercontent.com/14040923/50455859-92916780-0905-11e9-8a94-6c33aa6ec0aa.png)

**Comment by tberardini** [comment]
Bug looks fixed to me

**Comment by lreiser** [comment]
Close?
