### ISSUE TITLE
in progress submission not saved

### ISSUE THREAD

**Issue by tberardini** [tair/toastdos-back#326]
Previous implementation issue #186 

Old behavior:

Login, start submission, logout, login, see the partial submission and continue.
'Saving in progress...' notification while working every x amount of time (can't remember how frequent this was)

![image](https://user-images.githubusercontent.com/4998871/51949878-3a0d2880-23e3-11e9-9104-dbccb97097d6.png)

New behavior: 

Login, start submission, logout, login again and no partial submission saved.

**Comment by lreiser** [comment]
I can
login 
create a submission
enter some annotations (complete annotations)
logout
login
click on submit and view my in progress submission
This appears to be fixed.
