### ISSUE TITLE
Data validation/error messages not displaying for incomplete annotations on submission page

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#331]
Submitters should not be able to create an annotation that is lacking 
- A term (GO , PO or user defined)
-A method (from ECO or user defined)
-Evidence with entry (for IPI or IGI annotations

If one of the required fields is missing, an informative error message should appear if
1 the submitter tries to create another annotation and the previous annotation is incomplete
2 the submitter clicks review submission and one of the annotations is missing data

Try creating an annotation on 
http://toastdos.phoenixbioinformatics.org/

1.Login
2.Enter PMID = 27095837
3. Enter Locus=AT5G37820
4. Click add Annotation and create Process Annotation
5.Enter term=leaf development
6. Click Review Submission

You should see an error message pop up indicating method is required
see screenshots attached for examples.
![notermerror](https://user-images.githubusercontent.com/14040923/52678328-1f0fdd80-2ee6-11e9-8658-2e79b2365b1d.png)
![nomethoderror](https://user-images.githubusercontent.com/14040923/52678330-20410a80-2ee6-11e9-995b-1a6171d7c055.png)

**Comment by JKingSE** [comment]
#319

**Comment by lreiser** [comment]
yes sorry it is more or less a duplicate.

**Comment by lreiser** [comment]
I am thinking that enforcing the validation step before getting to the review submission phase would eliminate a lot of the subsequent issues surrounding submission review.

**Comment by qwertyflagstop** [comment]
Pushed a fix. Needs review

**Comment by lreiser** [comment]
I don't think this is working or perhaps not in all the right places.
I was able to move to the review screen from submission without actually entering in an annotation.
There should have been an error reported.


![screenshot_1611](https://user-images.githubusercontent.com/14040923/53776319-8e0ba100-3eaa-11e9-95b6-2a27085c7017.png)

**Comment by lreiser** [comment]
Errors on submission page that should generate a warning

1. No Publication Entered (DOI or PMID is required)
2. Invalid publication ID 
3. Invalid gene name ( validate name when adding a gene or when adding a name to  evidence with)
4. Missing term in annotation field (term is required)
5. Missing evidence in annotation field (evidence is required)
6. Missing Evidence with for IGI and ISS annotations (gene id is required)
7. Must have at least ONE complete annotation in order to review/submit. Can be of any type (comment, GO or PO)

for 5 and 6 there must be SOME value entered there but the values do NOT have to correspond to existing terms in the database.

**Comment by lreiser** [comment]
Partially fixed

1. No Publication Entered (DOI or PMID is required)
2. Invalid publication ID
3. Invalid gene name ( validate name when adding a gene or when adding a name to evidence with)
4. Missing term in annotation field (term is required)
5. Missing evidence in annotation field (evidence is required)

all display error messages. However, item 6 condition was not met.
I was able to move on to the submission review page without adding required 'evidence with' then when I tried to submit the annotations there was an error - the message displayed was 
 [object ProgressEvent]

![screenshot_1626](https://user-images.githubusercontent.com/14040923/53933517-8f2c0200-4053-11e9-9872-28573bb59dea.png)

**Comment by JKingSE** [comment]
The types of annotations I tried with missing information gave errors correctly and showed more informational error messages.  I can't guarantee I got every type of error though, this is something that will need more testing by sponsors as well.

**Comment by JKingSE** [comment]
Evidence with currently allows an empty field to be sent through if nothing was entered.

**Comment by lreiser** [comment]
Error message conditions are met.
![screenshot_1657](https://user-images.githubusercontent.com/14040923/55853349-9abc8e00-5b15-11e9-9f3f-044afda6cf68.png)
![screenshot_1658](https://user-images.githubusercontent.com/14040923/55853353-9c865180-5b15-11e9-91c4-9d8a9a5f1591.png)
![screenshot_1659](https://user-images.githubusercontent.com/14040923/55853354-9e501500-5b15-11e9-96b8-ba7bbb1b25e4.png)
