### ISSUE TITLE
Data download section is missing

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#332]
The current implementation does not include a link to download the approved/accepted GO/PO annotations in GAF format and approved comments in JSON format.

In the previous implementation (before the bug that prevented submissions from being approved) all approved annotations were pushed to the corresponding download format on a nightly basis.
The download data was available by clicking on the Download Data link in the menubar
Example...

http://toastdos.phoenixbioinformatics.org/exports

**Comment by JKingSE** [comment]
This is connected to #265 .  Ian and I will be meeting up and recreating this frontend this week.  The backend is prepared.

**Comment by lreiser** [comment]
It's really independent of the GPAD issue. Priority would be  restoring the existing data download functions.

**Comment by JKingSE** [comment]
You are correct.  I didn't really mean to say that they were the same issue, I was just putting them together as a note to myself because I plan to work on them at the same time.

**Comment by lreiser** [comment]
gotcha!

**Comment by lreiser** [comment]
2/20 testing
Form appears and there is data  in the GAF. Checking to see if I approve annotations today and that they are properly exported

**Comment by tberardini** [comment]
Header shows: !Last Updated: 2019-02-21

Also there are two annotations dated 2/20 that Leonore made to NIT1 that show up in the file.
Closing
