### ISSUE TITLE
Reviewing my own submission in progress 

### ISSUE THREAD

**Issue by tberardini** [tair/toastdos-back#333]
I entered two loci, At1g01040 and At2g23500 and then added one annotation per type 

![image](https://user-images.githubusercontent.com/4998871/52824510-c79c7980-306d-11e9-8a03-2e6d2302bf2c.png)

![image](https://user-images.githubusercontent.com/4998871/52824485-a50a6080-306d-11e9-92eb-79559e9b2e61.png)

![image](https://user-images.githubusercontent.com/4998871/52824500-bfdcd500-306d-11e9-838b-433b31065e14.png)

After clicking on Review Submission, I get this summary which tells me I don't have a valid locus, but as you can see from above, there is one!

![image](https://user-images.githubusercontent.com/4998871/52824542-ddaa3a00-306d-11e9-8943-c28cf07ca043.png)

(If there was a missing locus, then #319 would point this out before I could submit.)

**Comment by JKingSE** [comment]
Fixing #344 has appeared to fix this bug

**Comment by JKingSE** [comment]
Actually, upon further testing, entering in gene identifiers with lower case letters causes the website to not accept this information. Entering AT1G01040 or AT2G23500 does work.  I will keep this open for now until this is looked into

**Comment by lreiser** [comment]
Lets see if we can transform entries to upper case, should be case insensitive as far as data entry

**Comment by lreiser** [comment]
I am able to enter and annotate/review AGI Locus IDs that are a combination uppercase and lowercase letters.
@tberardini ..confirm? if so, pls close.

**Comment by tberardini** [comment]
confirmed.  I also tried with a mixed case UniProt ID, q56Y50, and that resolved nicely to Q56Y50.
