### ISSUE TITLE
Reset form not clearing all data (esp publication)

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#335]
I think this is a perhaps a recurrence of a previously reported issue.
Testing on Firefox.
Clicking reset form should clear any data from submission form.

This requires having some previously saved (in progress) submission*
1. Login via ORCID
2. Click submit
3. In progress submission is displayed
4. Click reset 
5. Form data except publication information (title, authors) disappears
6. Logout
7. Log in again
8. Repeat step 2: The previously uncleared data reappears.
9. Manually remove title and authors data from form field
10. Reset
- ONLY after manually removing the data from the authors/title field does the form completely reset and then when you log in the data is clear.

* example data

PMID: 30692244
GENE: AT4G08790
Annotation type: Molecular Function
Term: nitrile hydratase activity
Method: enzyme assay evidence used in manual assertion

**Comment by JKingSE** [comment]
Yes, I see this issue.  My initial guess would be that clicking "reset form" does not clear the draft that is saved.  We will take a look at what is causing it.

**Comment by lreiser** [comment]
On Staging Server
Log in with ORCID
Click on submission
View submission in progress

1. Submission in progress screen
![screenshot_1594](https://user-images.githubusercontent.com/14040923/53685968-6cf25700-3cd6-11e9-8d16-8ecfc00771f1.png)

2. Submission screen after clicking 'reset'
![screenshot_1595](https://user-images.githubusercontent.com/14040923/53685979-8bf0e900-3cd6-11e9-9c5a-9701e171f038.png)

On Production

1. In progress submission
![screenshot_1596](https://user-images.githubusercontent.com/14040923/53686005-e4c08180-3cd6-11e9-8b9c-b7f5da8d5e95.png)
2. After clicking reset
![screenshot_1597](https://user-images.githubusercontent.com/14040923/53686006-e9853580-3cd6-11e9-90e4-610465bfcde0.png)

**Comment by lreiser** [comment]
Resetting the form does not clear when EITHER a PMID or DOI is entered

e.g. DOI 
10.1093/pcp/pcz032

or PMID
30796840
But the PMID bug seems to seriously block other submissions from being entered.

**Comment by lreiser** [comment]
Entries with a PMID seem to be clearing fine however when I use a DOI , the hyperlink field seems to persist if I just click reset.

![screenshot_1648](https://user-images.githubusercontent.com/14040923/55442761-d929da00-5564-11e9-8e4d-a420497c8aea.png)

However, if I log out and log in again, the submission form is indeed blank. OR if I navigate away from the page and return to the page it is blank. Basically, fully clearing the form requires navigating away from the page, or refreshing the view. 
@tberardini , given that it is likely that either a person would be maybe correcting a PMID or DOI, or can reload, shall we call this done enough since it can be refreshed?

**Comment by tberardini** [comment]
> @tberardini , given that it is likely that either a person would be maybe correcting a PMID or DOI, or can reload, shall we call this done enough since it can be refreshed?

We can call this done enough. There's a workaround and there are bigger fish to fry.
