### ISSUE TITLE
Cannot 'add another annotation' when >1 gene

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#337]
Encountered a problem when trying to make more than one annotation when more than ONE gene has been added to the submission page

1. Login
2.Click submit (blank submission page)
3. Enter data
PMID:30589221
GENE1:AT2G01710
GENE2: AT1G62970
GENE3: AT5G04940
4. Create one annotation
5. Click add another annotation-
the only form field displayed is the annotation type drop down menu
Can't test more because the ORCID login stopped working

![screenshot_1567](https://user-images.githubusercontent.com/14040923/53070070-d4b4d080-3492-11e9-9d4a-43ecddcaca32.png)

**Comment by JKingSE** [comment]
When reproducing this bug, I see the same issue when the information of the annotation below the gene is filled in before clicking "Add Another Annotation".   If "Add Another Annotation" is clicked before putting information into the first annotation, then the fields for the second annotation come up.  This might help narrow down the cause.

**Comment by lreiser** [comment]
Expected Behavior from  (http://toastdos.phoenixbioinformatics.org/)

1. Entered PMID and 3 gene names 

![screenshot_1598](https://user-images.githubusercontent.com/14040923/53686360-d2e0dd80-3cda-11e9-91ab-ee0526bac978.png)

2. Enter annotation for 
AT2G01710
and another annotation for 
AT1G62970
![screenshot_1599](https://user-images.githubusercontent.com/14040923/53686381-1f2c1d80-3cdb-11e9-8fd2-e7a5550e9de8.png)

3. Review submission screen
![screenshot_1600](https://user-images.githubusercontent.com/14040923/53686387-2eab6680-3cdb-11e9-905b-23310593bd60.png)

**Comment by lreiser** [comment]
Observed Behavior from staging server (http://52.14.163.196:4200/submission)

1. After adding publication and 3 genes
![screenshot_1601](https://user-images.githubusercontent.com/14040923/53686423-9bbefc00-3cdb-11e9-850f-d8f205f69872.png)

2. After entering first annotation, there are no data entry fields for second annotation
![screenshot_1602](https://user-images.githubusercontent.com/14040923/53686435-bee9ab80-3cdb-11e9-926b-dff7bd1ebb9d.png)

**Comment by lreiser** [comment]
#346  again is a dependency here. 
The primary problem is resolved, in that I am able to add annotations for >1 gene. However, upon review the gene is undefined for every instance where I have to select anything but default option from the drop down menu.
![screenshot_1647](https://user-images.githubusercontent.com/14040923/55442568-04f89000-5564-11e9-98ff-51e6e58a2bea.png)
@tberardini  verify?

**Comment by tberardini** [comment]
I see the same behavior as @lreiser describes above.

**Comment by lreiser** [comment]
I am able to add 3 genes and add annotations of different types to each of the three genes.
![screenshot_1661](https://user-images.githubusercontent.com/14040923/55854101-7e6e2080-5b18-11e9-8f4b-eb6b824fdfce.png)
