### ISSUE TITLE
Cannot submit annotations of type 'comment'

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#339]
Attempting to submit a 'comment' annotation fails.
Review screen shows comment as 'undefined'

To reproduce
1.start new submission
2. Enter in PMID  30692538
3. Enter in Gene AT1G27690
4. Choose comment type annotation
5. Enter something "test comment"
6. Click Review annotation

Example data entry
![screenshot_1571](https://user-images.githubusercontent.com/14040923/53135256-6a05a280-352f-11e9-9262-0b74e7026bce.png)

Example of review screen
![screenshot_1572](https://user-images.githubusercontent.com/14040923/53135268-70941a00-352f-11e9-839d-cd7ad5835621.png)

**Comment by lreiser** [comment]
From current production version - expected behavior
1.Input data screen
![screenshot_1589](https://user-images.githubusercontent.com/14040923/53685868-2fd99500-3cd5-11e9-981e-1a9f2dad2338.png)

2 Review submission
![screenshot_1590](https://user-images.githubusercontent.com/14040923/53685872-45e75580-3cd5-11e9-89b0-2422d5a92b59.png)

3. Submission screen
![screenshot_1591](https://user-images.githubusercontent.com/14040923/53685879-5a2b5280-3cd5-11e9-9b65-c884aca9698c.png)

**Comment by JKingSE** [comment]
It now seems to be possible to submit comment annotations

**Comment by lreiser** [comment]
verified that submitting a comment works.
