### ISSUE TITLE
Auto-Population of Gene Fields in Protein Interaction Annotation Doesn't Send Info

### ISSUE THREAD

**Issue by JKingSE** [tair/toastdos-back#344]
#313
The first gene appears to auto populate with the first annotation, but the information isn't actually sent over when the annotation is submitted. For the information to be sent over, the user still has to click on the dropdown and select the first annotation in the Gene 1 box. Then it will work which might be why Nick saw it working.

PMID = 27095837
Add Locus 1 = AT5G37820
Add Locus 2 = AT5G37810
Add a Protein interaction annotation.
For Gene 1, select AT5G37810 and then switch it back to AT5G37820.
For Gene 2, select AT5G37820.
Clicking submit should now work
It appears that the information only fills into the form when the option is changed and not in auto-population.

**Comment by lreiser** [comment]
This may also be at the root of Tanyas #333

**Comment by lreiser** [comment]
Still not working as expected. 
If I choose protein interaction ,leave the first gene as is, and select the second gene from the drop down menu, the review screen shows as undefined.
![screenshot_1645](https://user-images.githubusercontent.com/14040923/55442159-4ab45900-5562-11e9-9814-6a65e32acd90.png)

If I go back and edit the submission and specifically SELECT both genes, then the review screen displays them as BOTH undefined.
![screenshot_1646](https://user-images.githubusercontent.com/14040923/55442210-8f3ff480-5562-11e9-8857-c6ba77f8d37b.png)

There seems to be a dependency on #346.  Basically which ever gene is 'manually selected' disappears in the review screen.

**Comment by lreiser** [comment]
@tberardini verify?

**Comment by tberardini** [comment]
I see the same behavior that @lreiser observed.

**Comment by lreiser** [comment]
I am able to manually select different genes from the drop down list and those genes are properly represented on the review summary page.
