### ISSUE TITLE
Manual selection of which gene is being sent through shows up as undefined in annotation review

### ISSUE THREAD

**Issue by JKingSE** [tair/toastdos-back#346]
When changing the gene associated with an annotation, going to review the submission shows those changed genes as 'undefined'. 

Repro Steps:
1. add PMID = 27095837
2. add Add Locus 1 = AT5G37820
3. add Add Locus 2 = AT5G37810
4. Create a Molecular Function Annotation
5. Change the gene to display Gene 2 from above
![newAreaIssue](https://user-images.githubusercontent.com/17603890/55432746-af22e880-5561-11e9-8f37-169709570a98.png)
6. Click Review Submission, notice that the gene is undefined in the Annotation section
![newAreaIssue2](https://user-images.githubusercontent.com/17603890/55432782-c9f55d00-5561-11e9-9569-15607ee6456f.png)
7.  Click Submit Annotations, submission goes through and the annotation has correct information in curation.

Here is the request sent when submitting the annotation:
`{"publicationId":"27095837","genes":[{"locusName":"AT5G37810","geneSymbol":"SMT","fullName":"SOMETHING"},{"locusName":"AT5G37820","geneSymbol":"","fullName":""}],"annotations":[{"type":"MOLECULAR_FUNCTION","data":{"locusName":"AT5G37820","isEvidenceWithOr":true,"keyword":{"id":14495},"method":{"id":51389}},"id":11}]}`

**Comment by JKingSE** [comment]
The current thing blocking issue #313 from being completed could be the same issue as this

**Comment by lreiser** [comment]
this seems to be fixed.
