### ISSUE TITLE
Curated Annotations should be attributed to the submitter, not the curator who reviewed them

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#347]
I noticed that the in the display of search results, the name associated with the curated submission is the curator, not the submitter.

After reviewing and accepting annotations submitted by Ian , I looked to see what displayed in the search and found that the attribution was to me, not Ian. 

Need to verify that the submitter is associated in the results and GAF file when it is exported.

![screenshot_1649](https://user-images.githubusercontent.com/14040923/55443177-9ec13c80-5566-11e9-9c04-8af8f5068106.png)

**Comment by lreiser** [comment]
will advance to critical if it turns out that the GAF format also has same error.

**Comment by lreiser** [comment]
After checking the GAF file  on the correct server (http://3.16.181.171:4200/search)
it appears that the GAF file is also incorrectly attributing the submission to me. The ORCiD associated with the highlighted entry is mine.

![screenshot_1655](https://user-images.githubusercontent.com/14040923/55835992-18f74100-5ad2-11e9-8eb6-9fb447b0f2e1.png)

Also note there is some weirdness with the results of the search. If you just type in a letter (say s) there are a large number of seemingly incomplete data rows. Will look into this as separate issue.

**Comment by JKingSE** [comment]
I can confirm that Leonore curating my submitted annotation changed the database itself to mark her as the submitter.  So this is either a problem with the front-end sending in the curator as the submitter and overwriting the original submitter, OR the backend takes in the information and overwrites it when it saves the new status.  I'll look into the backend to see if the problem lies there

**Comment by JKingSE** [comment]
This bug is ready to be checked.  Any previous annotations that had been changed are going to stay changed, but new submissions from this point on should not see the submitter change when they are curated.

**Comment by lreiser** [comment]
tested  w three annotations submitted by JK today 
JK orcid =0000-0001-9947-4545
seems to be fine.
![screenshot_1683](https://user-images.githubusercontent.com/14040923/56540010-54efc480-651c-11e9-88e6-4c0c25bb1890.png)
