### ISSUE TITLE
Curation page with multiple genes shows wrong gene

### ISSUE THREAD

**Issue by JKingSE** [tair/toastdos-back#348]
Description:  For curations with multiple genes and multiple annotations, all annotations show their information auto-filled to the first gene whether or not they had different genes submitted.  However going into the review page of the curation does show the correct gene.

Repro Steps:
1. Go to Submission
2. Enter Info: 
PMID = 27095837
Add Gene 1 = AT5G37820
Add Gene 2 = AT5G37810
3. Add multiple annotations with at least one of them pointing at gene AT5G37810
4. Fully submit the annotations
5. Go to curation
6. Click on the submission just made
7. Look at the annotations, all of them will display the gene AT5G37820 even though at least one had AT5G37810 selected
8. Click review changes, the relevant annotation will display AT5G37810 in the review page

This is a picture of the curation page for the submission
![curationIssueA](https://user-images.githubusercontent.com/17603890/55817349-5784ff80-5ac2-11e9-8c54-bb7f451876f7.png)

This is a picture of the review of the curation page above
![curationReviewA](https://user-images.githubusercontent.com/17603890/55817373-6a97cf80-5ac2-11e9-857b-cf8c6c17305e.png)

**Comment by lreiser** [comment]
Confirmed this bug is fixed.
@tberardini ... agreed if so then close..

**Comment by tberardini** [comment]
Agreed.
