### ISSUE TITLE
Review screen does not display symbol/full name when only symbol is entered.

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#352]
Adding this for tracking purposes later.

When a gene is added and only a gene symbol is entered, but not a full name, the symbol is not displayed on the review screen. 
To reproduce.
1. Enter publication (10.1016/j.molp.2019.03.012)
2.Enter locus ID (e.g.AT1G65250)
3. Enter only a symbol (e.g. SRK1)
4. Enter an annotation (any type)
5. click review.
The gene symbol will be missing.

![screenshot_1674](https://user-images.githubusercontent.com/14040923/56245069-4e140e00-6053-11e9-9985-15a04292f0c2.png)

**Comment by JKingSE** [comment]
After my testing, it now seems to display partial information when only one of the areas is filled out

**Comment by lreiser** [comment]
Confirmed- now displays symbol if no full name included.
![screenshot_1687](https://user-images.githubusercontent.com/14040923/56540709-5de19580-651e-11e9-9173-a4fcf6adc171.png)

@tberardini  agreed?

**Comment by tberardini** [comment]
I can't confirm because I can't access the 'Submit' functionality (see conversation in Slack).

**Comment by lreiser** [comment]
@tberardini  use http://3.16.181.171:4200/ for testing.

**Comment by tberardini** [comment]
Verified on http://3.16.181.171:4200/
