### ISSUE TITLE
TAIR API wrapper

### ISSUE THREAD

**Issue by JDonut** [tair/toastdos-back#53]
TAIR provides information on the Arabidopsis Thaliana. It has two endpoints:
 - GET https://www.arabidopsis.org/locus/{name}
 - GET https://www.arabidopsis.org/symbols/{symbol}

We want to be able to search a locus by it's name, and by it's symbol

**Comment by bob-muller** [comment]
We're changing /locus to /loci for consistency with our newer API standard. Also, we're adding the taxon to the returned JSON. This change is on our test system now (demotair) and will be generally available when it passes system test by our curators.

   --Bob Muller

**Comment by bob-muller** [comment]
We've released the /loci/{name} web service to production, please use that now.
