### ISSUE TITLE
NCBI Taxon API wrapper

### ISSUE THREAD

**Issue by JDonut** [tair/toastdos-back#55]
The NCBI taxon database should let us search a gene by its name, then return the taxon (organism) the gene belongs to. We need a wrapper for that functionality in our system.

**Comment by tberardini** [comment]
The NCBI taxon database is only a database of taxa, not genes.  I think that the webservices you will use for RNACentral, UniProtKB, and TAIR should return the taxon of the organism the record in those databases belongs to. NCBI Taxonomy can provide you with the database standard identifiers for these taxa.  For example, Arabidopsis thaliana = 3702.

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=3702

For example, the Uniprot service returns:

**Comment by bob-muller** [comment]
And Just FYI, TAIR doesn't have the NCBI taxon id in its database at this point for at least the key taxa, not sure why.

**Comment by tberardini** [comment]
We do have the field in the TAIR Taxon table and it's filled for 28/72 species.  I'll fill in what I can. (unrelated to your work, RIT team :) )

**Comment by bob-muller** [comment]
Could be related if it would be useful to put the Genbank/NCBI id into the web service data. Simple addition.
