### ISSUE TITLE
Add internal logging to responses

### ISSUE THREAD

**Issue by Mimickal** [tair/toastdos-back#61]
Errors are reported to the client, but in production this will not notify us of issues the backend runs into (especially login errors). We want to log these errors so we can diagnose and debug issues clients might be running into.

After the refactoring task (See tair/toastdos-back#26 ) all responses should be in a single utility file.

**Comment by Laludia** [comment]
http://stritti.github.io/log4js/docu/users-guide.html
Log4js?

**Comment by Laludia** [comment]
https://www.npmjs.com/package/express-logger
express-logger (maybe this one is closest)

**Comment by Laludia** [comment]
https://github.com/expressjs/morgan
Morgan

**Comment by Laludia** [comment]
Guide to Logging in Node.js
https://www.loggly.com/ultimate-guide/node-logging-basics/

**Comment by Laludia** [comment]
https://github.com/winstonjs/winston
Winston(in WebPack)
