### ISSUE TITLE
SQL injection vulnerability in Keyword controller

### ISSUE THREAD

**Issue by JDonut** [tair/toastdos-back#66]
The following two lines should be using prepared statements with bindings. Currently we're just sticking user input into the query, because @JDonut is dumb.
```js
qb.where('name', 'LIKE', `%${req.body.substring}%`);
qb.where('keyword_type_id', '=', req.body.keyword_type);
```

A cursory look at the knex docs suggests this might be bound for us, but let's make sure this isn't a vulnerability.

**Comment by Laludia** [comment]
KnexRaw: https://github.com/tgriesser/knex/issues/718
